### ISSUE TITLE
Feature: Add options for categories

### ISSUE THREAD

**Issue by p3lim** [p3lim-wow/LibContainer#49]
Needs to fulfill the following criterias/needs:
- [ ] Creating custom categories (#3)
- [x] Renaming categories (even the default ones?) (#44)
- [x] Enabling/disabling categories (except Bank, Reagent Bank and Inventory (ids 1 and 1002))
- [ ] Allowing categories to bypass the "New" category (#13)

Closing the other relevant issues in favor of this one.

**Comment by p3lim** [comment]
GUI configurations are up to the layout to implement. LibContainer should facilitate the backend needed to configure, nothing more.
