### ISSUE TITLE
8.0 Rewrite Checklist

### ISSUE THREAD

**Issue by p3lim** [p3lim-wow/LibContainer#65]
Things left to do before we'll consider it "ready" to use.  
Listed mostly to keep me sane.

Feel free to contribute in any way, may it be PRs, suggestions or general feedback.  
This is the time to do so.

### TODO (slightly prioritized list)

- [x] bags
- [x] slots
- [x] containers
- [x] categories
- [x] optimize BAG_UPDATE https://github.com/p3lim-wow/LibContainer/commit/b7c4079fdba7df4ca95ba5c22b67e0d093dfd5b0
- [x] rework itemMixin, cache correctly https://github.com/p3lim-wow/LibContainer/commit/17a9fea6e603e89afb5e56d34c40fa7298a13d8b
	- maybe use more of C_Item/ItemMixin?
- [x] add shift modifier for compare tooltip instead of the onupdate default https://github.com/p3lim-wow/LibContainer/commit/58186728ba37477bbd6abb4b441ae11b0a14bd56
- [x] fix inspect cursor https://github.com/p3lim-wow/LibContainer/commit/987b2be8f0ed11069c08ca5e9521460ef57f9f94
- [x] disable blizzard's bags and use ours https://github.com/p3lim-wow/LibContainer/commit/96774bac81776453ac7e44976cdf138554800878
- [x] documentation
	- [x] document methods https://github.com/p3lim-wow/LibContainer/commit/739cd2ca39a4335c5fd2c5bf2f5ef30744a7c99c
	- [ ] pretty up the docs
		- crosslinks
		- page headers
	- [x] find a suitable lexer (or write our own) https://github.com/p3lim-wow/LibContainer/commit/5b87df0cea9323738317997461311dd80145c922
		- want to document to one file per 'mixin', like how [the wiki is set up for](https://github.com/p3lim-wow/LibContainer/wiki)
	- [x] on master push use travis + github deploy key to push to wiki https://github.com/p3lim-wow/LibContainer/commit/02e36a375a55a59c496cf43110190c7c591ce0e1
- [x] add assertions https://github.com/p3lim-wow/LibContainer/commit/c47ac5cb136539325445847e145f9fc119c64d10
- [x] implement category ignore functions (on parent) https://github.com/p3lim-wow/LibContainer/commit/658e45e3760c3c7e9b96a488aaed1b5f68205692
- [ ] implement the db + methods
	- SetKnown(itemID)
		- basically a proxy for SetCategory where it'll figure out the best one itself bsed on sort functions
	- SetCategory(itemID, categoryIndex)
	- container order
	- category priority
- [x] dropdown
	- let the layout deal with this, we've added all the methods needed
		- I don't want to force upon layouts to use a certain dropdown lib
- [x] implement widgets
	- [x] free slots (inventory) https://github.com/p3lim-wow/Backpack/commit/3c66e36a7164f5cfbd593c10f51368185d77ac48
		- [x] needs to be moved into LibContainer https://github.com/p3lim-wow/LibContainer/commit/0a105c3154305c30ef7901cbb3b2e9cfa61fe535
	- [x] currencies (inventory) https://github.com/p3lim-wow/LibContainer/commit/a4780f13988f667cd07a94b9ce1e80928068aac0
	- [x] money (inventory) https://github.com/p3lim-wow/LibContainer/commit/fb4f60072afa257b92d931da2b1c543f5237f8fe
	- [x] search (inventory) https://github.com/p3lim-wow/LibContainer/commit/1f155a005f3d4351c296a703040abde6bf9ddef0
	- [x] bags (inventory) https://github.com/p3lim-wow/LibContainer/commit/cbe4d42bacd9c7478285387aebef4021611bed9f + https://github.com/p3lim-wow/LibContainer/commit/ce96520ea0bedf188a757e0d02ff867d1898e3b7
	- [x] restack (inventory) https://github.com/p3lim-wow/LibContainer/commit/d23db32b64b33cf80f62a3d7f81c38dd16df1042
	- [x] auto-vendor (junk) https://github.com/p3lim-wow/LibContainer/commit/280ccb49b42fcc1b0bdf490ddd0ede5063b0eb16
	- [x] mark new as known (new) https://github.com/p3lim-wow/LibContainer/commit/168f126aae832d8454b77aa06fc7f78cd2b9a614
	- [x] auto-deposit (reagents) https://github.com/p3lim-wow/LibContainer/commit/da86ab10c509702d20f97d355224f7d807b4fa50
	- [x] deposit all (reagents) https://github.com/p3lim-wow/LibContainer/commit/1b00cc94917f6153f5e5e5f0f5c9f08bd9d3a722
- [x] add bank support https://github.com/p3lim-wow/LibContainer/commit/38389a410d708d5f78a0a984ecfa66a0817799d1
- [x] add reagent bank support https://github.com/p3lim-wow/LibContainer/commit/e4b42041042388526fda97178d857a48a47e90df
- [x] go through existing issues
- [x] move translations to its own directory https://github.com/p3lim-wow/LibContainer/commit/f8d73ab893ab3a9642f79e0cd5b9e279fcdcfcb1
	- just to make it easier for contributors to find everything
- [ ] add remote bank support (?)
- [ ] add tooltip for which characters has item (ItemRef + tooltip) (?)
- [ ] restrict API further (?)

### Optimization pass required

- [x] categories/defaultSort order
	- probably as close to perfect as we want it
- [x] slot/UpdateCategory
- [x] container/UpdateSize
	- maybe add some logic that checks if there was more/less rows
		- based on that we can decide if we want to resize AND if we need to reposition containers
- [x] container/UpdateSlotPositions
	- probably as close to perfect as we can get it
- [x] container/UpdateContainerPositions
	- this one is particularily messy imo

**Comment by p3lim** [comment]
Considered feature-complete for now, still a few bugs and kinks left to fix before release.
